# netlify.toml
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # optional, fails build when a category is below a threshold
  [plugins.inputs.thresholds]
    performance = 0.85
    accessibility = 0.85
    best-practices = 0.85
    seo = 0.9


  # optional, deploy the lighthouse report to a path under your site
  [plugins.inputs]
    output_path = "reports/lighthouse.html"


# Production context:
[context.production]

  [[context.production.plugins]]
    package = "netlify-build-plugin-pushover"

      [context.production.plugins.inputs]
        successMessage="Success msg from Production 🥳"
        errorMessage="Error msg from Production 🚨"


# Deploy Preview context:
[context.deploy-preview]

  [[context.deploy-preview.plugins]]
    package = "netlify-build-plugin-pushover"

      [context.deploy-preview.plugins.inputs]
        successMessage="Success msg from deploy preview 🥳"
        errorMessage="Error msg from deploy preview 🚨"


