backend:
  name: github
  repo: kryptokrona/xkr-website
  branch: main
collections:
  - name: articels
    label: Articels
    folder: src/routes/blog
    create: true
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
media_folder: "static/uploads"
public_folder: "/uploads"

# site_url: https://kryptokrona.org
# display_url: https://kryptokrona.org
# logo_url: https://your-site.com/images/logo.svg